services:
  adguardhome:
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - ${TCP_PORT}:53/tcp # plain dns over tcp
      - ${UDP_PORT}:53/udp # plain dns over udp
      - ${WEB_PORT}:80/tcp # http web interface
      - ${WEB_INIT_PORT}:3000/tcp # initial setup web interface
    volumes:
      - ./config:/opt/adguardhome/conf # app configuration
      - ./work:/opt/adguardhome/work # app working directory
